<a href="https://colab.research.google.com/github/snehalamba8/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [ ]:
import numpy as np

In [ ]:
a=np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [ ]:
a2=a.reshape(2, 3)
print(a2)

[[1 2 3]
 [4 5 6]]


Q2

In [ ]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(a)
print(b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [ ]:
common = np.intersect1d(a, b)
print(common)

[2 4]


Q3

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)


[ 2  6  1  9 10  3 27]


In [ ]:
ans = a[(a >= 5) & (a <= 10)]
print(ans)

[ 6  9 10]


Q4

In [ ]:
a = np.arange(15)

In [ ]:
np.set_printoptions(threshold=6)

print(a)

[ 0  1  2 ... 12 13 14]
